services:

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_HTTP_SERVER_ALLOWED_HOSTS=mlflow,localhost,127.0.0.1
    volumes:
      # Map local mlruns folder so models persist between restarts
      - ./mlruns:/app/mlruns
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: mlflow server --serve-artifacts --host 0.0.0.0 --port 5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    command: >
      sh -c "python train.py && uvicorn main:app --host 0.0.0.0 --port 8000"
        
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      # CRUCIAL: Docker internal network routing!
      - API_URL=http://backend:8000 
    depends_on:
      - backend